export type Job = {
  id: string;
  title: string;
  industry: string; // industry slug
  industryName: string;
  location: string;
  type: "Full-time" | "Contract" | "Travel" | "Part-time" | "Temp-to-hire";
  remote: "On-site" | "Hybrid" | "Remote";
  salary: string;
  posted: string;
  summary: string;
  responsibilities: string[];
  requirements: string[];
  featured?: boolean;
};

export const jobs: Job[] = [
  {
    id: "rn-icu-chicago",
    title: "ICU Registered Nurse",
    industry: "healthcare",
    industryName: "Healthcare",
    location: "Chicago, IL",
    type: "Full-time",
    remote: "On-site",
    salary: "$85k – $105k",
    posted: "2 days ago",
    summary: "Join a Level I trauma center's intensive care unit delivering critical care to high-acuity patients.",
    responsibilities: ["Provide direct patient care in the ICU", "Monitor and adjust care plans", "Collaborate with the multidisciplinary care team", "Maintain accurate clinical documentation"],
    requirements: ["Active RN license (IL)", "BLS & ACLS certification", "2+ years ICU experience", "BSN preferred"],
    featured: true,
  },
  {
    id: "travel-nurse-medsurg",
    title: "Travel Nurse — Med/Surg",
    industry: "healthcare",
    industryName: "Healthcare",
    location: "Multiple states",
    type: "Travel",
    remote: "On-site",
    salary: "$2,400 – $3,000 / wk",
    posted: "4 days ago",
    summary: "13-week travel assignments with housing stipend and full compliance support.",
    responsibilities: ["Deliver med/surg nursing care", "Adapt quickly to new facilities", "Support unit staffing needs"],
    requirements: ["Active multi-state (compact) RN license", "1+ year med/surg experience", "Flexibility to relocate"],
    featured: true,
  },
  {
    id: "site-supervisor",
    title: "Construction Site Supervisor",
    industry: "construction",
    industryName: "Construction",
    location: "Naperville, IL",
    type: "Full-time",
    remote: "On-site",
    salary: "$70k – $92k",
    posted: "1 week ago",
    summary: "Oversee daily operations on a commercial build, ensuring safety, quality, and schedule.",
    responsibilities: ["Supervise trades and subcontractors", "Enforce OSHA safety standards", "Track progress against schedule"],
    requirements: ["5+ years construction experience", "OSHA 30 certification", "Blueprint reading"],
  },
  {
    id: "journeyman-electrician",
    title: "Journeyman Electrician",
    industry: "electrical",
    industryName: "Electrical",
    location: "Milwaukee, WI",
    type: "Contract",
    remote: "On-site",
    salary: "$38 – $46 / hr",
    posted: "3 days ago",
    summary: "Commercial and industrial electrical installation on a 6-month infrastructure contract.",
    responsibilities: ["Install conduit, wiring, and panels", "Read electrical schematics", "Ensure code compliance"],
    requirements: ["Valid journeyman license", "3+ years commercial experience", "Own hand tools"],
    featured: true,
  },
  {
    id: "tax-accountant",
    title: "Senior Tax Accountant",
    industry: "tax-legal",
    industryName: "Tax & Legal",
    location: "Chicago, IL",
    type: "Full-time",
    remote: "Hybrid",
    salary: "$78k – $98k",
    posted: "5 days ago",
    summary: "Lead corporate and individual tax engagements for a growing mid-market advisory firm.",
    responsibilities: ["Prepare and review tax returns", "Advise clients on tax strategy", "Research tax regulations"],
    requirements: ["CPA (or CPA-eligible)", "4+ years public accounting", "Strong knowledge of federal & state tax"],
  },
  {
    id: "commercial-project-manager",
    title: "Commercial Project Manager",
    industry: "construction",
    industryName: "Construction",
    location: "Chicago, IL",
    type: "Full-time",
    remote: "On-site",
    salary: "$95k – $130k",
    posted: "1 day ago",
    summary: "Lead ground-up commercial builds from preconstruction through closeout, owning budget, schedule, and safety.",
    responsibilities: ["Manage project budgets and schedules", "Coordinate subcontractors and vendors", "Enforce safety and quality standards", "Report progress to stakeholders"],
    requirements: ["7+ years construction PM experience", "PMP or OSHA 30 preferred", "Strong knowledge of commercial builds", "Bachelor's in construction management a plus"],
    featured: true,
  },
  {
    id: "master-electrician",
    title: "Master Electrician",
    industry: "electrical",
    industryName: "Electrical",
    location: "Aurora, IL",
    type: "Full-time",
    remote: "On-site",
    salary: "$40 – $55 / hr",
    posted: "6 days ago",
    summary: "Lead electrical installations and inspections across commercial and industrial projects.",
    responsibilities: ["Plan and oversee electrical installations", "Ensure NEC code compliance", "Mentor journeymen and apprentices", "Coordinate permits and inspections"],
    requirements: ["Master electrician license", "8+ years electrical experience", "Blueprint and schematic reading", "Strong safety record"],
  },
  {
    id: "paralegal-corporate",
    title: "Corporate Paralegal",
    industry: "tax-legal",
    industryName: "Tax & Legal",
    location: "Chicago, IL",
    type: "Full-time",
    remote: "Hybrid",
    salary: "$62k – $80k",
    posted: "1 week ago",
    summary: "Support corporate transactions, entity management, and compliance for an in-house legal team.",
    responsibilities: ["Draft and manage corporate documents", "Maintain entity records", "Support M&A due diligence"],
    requirements: ["Paralegal certificate", "3+ years corporate law", "Excellent attention to detail"],
  },
  {
    id: "lpn-longterm-care",
    title: "Licensed Practical Nurse (LPN)",
    industry: "healthcare",
    industryName: "Healthcare",
    location: "Skokie, IL",
    type: "Part-time",
    remote: "On-site",
    salary: "$28 – $34 / hr",
    posted: "3 days ago",
    summary: "Provide compassionate long-term care nursing with flexible part-time scheduling.",
    responsibilities: ["Administer medications", "Monitor resident health", "Support daily care activities"],
    requirements: ["Active LPN license (IL)", "Long-term care experience preferred", "Compassionate bedside manner"],
  },
  {
    id: "controls-technician",
    title: "Industrial Controls Technician",
    industry: "electrical",
    industryName: "Electrical",
    location: "Gary, IN",
    type: "Temp-to-hire",
    remote: "On-site",
    salary: "$32 – $40 / hr",
    posted: "2 weeks ago",
    summary: "Maintain and troubleshoot PLC-driven control systems in a manufacturing environment.",
    responsibilities: ["Troubleshoot PLC/HMI systems", "Perform preventive maintenance", "Document repairs"],
    requirements: ["Associate degree or equivalent", "PLC experience (Allen-Bradley)", "Electrical troubleshooting skills"],
  },
  {
    id: "carpenter-commercial",
    title: "Commercial Carpenter",
    industry: "construction",
    industryName: "Construction",
    location: "Chicago, IL",
    type: "Contract",
    remote: "On-site",
    salary: "$30 – $38 / hr",
    posted: "4 days ago",
    summary: "Rough and finish carpentry on commercial interior build-outs.",
    responsibilities: ["Frame walls and install fixtures", "Read construction drawings", "Maintain a safe work area"],
    requirements: ["4+ years carpentry", "Own tools", "Reliable transportation"],
  },
  {
    id: "senior-tax-manager",
    title: "Senior Tax Manager",
    industry: "tax-legal",
    industryName: "Tax & Legal",
    location: "Chicago, IL",
    type: "Full-time",
    remote: "Hybrid",
    salary: "$115k – $145k",
    posted: "5 days ago",
    summary: "Manage tax strategy and compliance for corporate clients at a growing advisory firm.",
    responsibilities: ["Review complex corporate and individual returns", "Advise clients on tax planning", "Manage and mentor a team of accountants", "Research evolving tax regulations"],
    requirements: ["CPA required", "8+ years public accounting", "Team leadership experience", "Deep federal & state tax knowledge"],
  },
];

export const jobTypes: Job["type"][] = ["Full-time", "Contract", "Travel", "Part-time", "Temp-to-hire"];
export const workModes: Job["remote"][] = ["On-site", "Hybrid", "Remote"];

export const getJob = (id: string) => jobs.find((j) => j.id === id);
